### ISSUE TITLE
free-dristro logos

### ISSUE THREAD

**Issue by arkhan** [fabianalexisinostroza/Antu-U#30]
Un saludo, aquí molestandote con otra issue, pero podrias agregar los iconos correspondientes para las siguientes distros:
http://www.gnu.org/distros/free-distros.es.html

Gracias...

**Comment by fabianalexisinostroza** [comment]
voy a considerar tu solicitud, de hecho solo tengo trisquel así que para la siguiente versión estarán todos ;)

**Comment by fabianalexisinostroza** [comment]
![screenshot_20160124_232603](https://cloud.githubusercontent.com/assets/14989730/12541190/1289d740-c2f2-11e5-8559-5c493c52ab34.png)

**Comment by arkhan** [comment]
cool.... gracias

**Comment by SalahAdDin** [comment]
Estos no eran los íconos El General?

**Comment by fabianalexisinostroza** [comment]
Si, pero han cambiado de nombre, si quieres más información de las razones https://pinguinosyuncafe.wordpress.com/

**Comment by F4kund0** [comment]
¿De casualidad no tendrás la versión anterior de los íconos y del tema para Plasma? Me refiero a cuando se llamaban ElGeneral. Me gusta más esa versión...

**Comment by fabianalexisinostroza** [comment]
No, pero si quieres las versiones anteriores de los iconos, es cosa de ir a quienes lo han forkeado. Del tema plasma hay una versión adaptada en kde-look dentro de los comentarios con algunos elementos del tema anterior.

**Comment by F4kund0** [comment]
Qué lástima. De hecho los íconos no son tanto problema porque prácticamente es el mismo diseño, y me gustan. Lo que sí quisiera tener es el tema plasma anterior. Gracias :)

**Comment by fabianalexisinostroza** [comment]
encontré un backup del tema (supongo que es, porque tiene el nombre anterior) lo subí a owncloud https://cloud.openmailbox.org/index.php/s/pFYWAofMSdEk150

**Comment by F4kund0** [comment]
De hecho lo es. Qué suerte, muchísimas gracias :smile:

**Comment by feskyde** [comment]
Para simplificar las cosas y no tener la necesidad de guardar una copia, los commits anteriores al cambio de nombre (del [`250ac6f`](https://github.com/fabianalexisinostroza/Antu-U/commit/250ac6fe52ddf528d9cd2c6b30426f346c3da431) para atrás) todavia llevan el nombre de El General
